defaults:
  - data_paths: default
  - preprocessing: default
  - model: random_forest
  - _self_

project_name: "ExoplanetDetectionKepler"
random_state: 42
test_size: 0.2

mlflow_experiment_name: "Exoplanet Detection Pipeline"
mlflow_tracking_uri: "sqlite:///mlflow.db"

base_dir: ???

data_dir_rel: "data"
model_dir_rel: "models"
reports_dir_rel: "reports"
log_file_rel: "logs/pipeline.log"

prediction_sample_size: 5

tuning:
  cv_folds: 5
  cv_n_jobs: -1
  n_trials: 50
  direction: "maximize"
  metric_to_optimize: "cv_roc_auc_mean"

data_dir: ???
model_dir: ???
reports_dir: ???
log_file: ???
model_path: ???
scaler_path: ???
imputer_path: ???
training_columns_path: ???
poly_features_path: null
