# This file defines the 'preprocessing' group, selected by 'default' in main config
target_column: "koi_disposition"
positive_labels: ["CONFIRMED", "CANDIDATE"]
negative_label: "FALSE POSITIVE"
features_to_drop:
  - "rowid"
  - "kepid"
  - "kepoi_name"
  - "kepler_name"
  - "koi_pdisposition"
  - "koi_score"
  - "koi_tce_delivname"
  - "koi_comment"
  - "koi_sparprov"
apply_polynomial_features: false
polynomial_degree: 2